package com.chala.posapp.service;
import com.chala.posapp.audit.Audited; import com.chala.posapp.dto.reorder.*; import com.chala.posapp.entity.*; import com.chala.posapp.entity.reorder.*; import com.chala.posapp.entity.supplier.SupplierItem; import com.chala.posapp.exception.*; import com.chala.posapp.repository.*; import com.chala.posapp.util.*; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.math.*; import java.time.LocalDateTime; import java.util.*; import java.util.stream.Collectors;
@Service @RequiredArgsConstructor
public class ReorderPlanService {
 private final ReorderPlanRepository repository; private final SupplierItemReadRepository supplierItems; private final SupplierRepository suppliers; private final ItemRepository items; private final RecipeIngredientRepository recipeIngredients; private final StockBatchRepository stockBatches; private final NewReportService reports; private final SecurityUtils security;
 @Transactional @Audited(entity="REORDER_PLAN",action="CREATE")
 public ReorderPlanResponse create(ReorderPlanRequest request){
  if(request==null||request.name()==null||request.name().isBlank())throw new BadRequestException("name is required");
  Long branch=security.enforceBranchAccess(request.branchId()); User user=security.getCurrentUser();
  var forecast=reports.demandForecast(branch,request.forecastDays(),request.targetCoverDays(),null,null,null,null,true);
  ReorderPlan plan=ReorderPlan.builder().name(request.name().trim()).branchId(branch).forecastDays(request.forecastDays()).targetCoverDays(request.targetCoverDays()).createdByUserId(user.getId()).createdByUsername(user.getUsername()).notes(request.notes()).build();
  Map<Long,DemandAccumulator> demand=new LinkedHashMap<>();
  for(var forecastItem:forecast.getItems()){
   Item item=items.findById(forecastItem.getItemId()).orElse(null); if(item==null||item.getItemType()==ItemType.SERVICE)continue;
   if(item.getItemType()==ItemType.RECIPE){for(RecipeIngredient ingredient:recipeIngredients.findByParentItemId(item.getId())){long recipeDemand=Math.multiplyExact(forecastItem.getProjectedDemandBase(),ingredient.getQuantity().longValue());demand.computeIfAbsent(ingredient.getIngredientId(),ignored->new DemandAccumulator()).addRecipe(recipeDemand,forecastItem.getConfidence());}}
   else demand.computeIfAbsent(item.getId(),ignored->new DemandAccumulator()).addDirect(forecastItem.getProjectedDemandBase(),forecastItem.getConfidence());
  }
  for(var entry:demand.entrySet()){Item item=items.findById(entry.getKey()).orElse(null);if(item==null||item.getItemType()==ItemType.SERVICE||item.getItemType()==ItemType.RECIPE)continue;DemandAccumulator d=entry.getValue();long onHand=Optional.ofNullable(stockBatches.getTotalQuantityByItemAndBranch(branch,item.getId())).orElse(0);long suggested=Math.max(0,Math.subtractExact(d.total(),onHand));if(suggested==0)continue;BigDecimal display=QuantityConversionUtil.toDisplayQuantity(item,Math.toIntExact(suggested));SupplierItem mapping=supplierItems.findByItemIdAndSupplierActiveTrueOrderByPrimarySupplierDescIdAsc(item.getId()).stream().findFirst().orElse(null);var supplier=mapping==null?null:mapping.getSupplier();BigDecimal cost=mapping!=null&&mapping.getLastBuyingPrice()!=null?BigDecimal.valueOf(mapping.getLastBuyingPrice()):item.getCostPrice();plan.getLines().add(ReorderPlanLine.builder().plan(plan).itemId(item.getId()).itemName(item.getName()).itemType(item.getItemType()).unit(QuantityConversionUtil.primaryDisplayUnit(item).name()).supplierId(supplier==null?null:supplier.getId()).supplierName(supplier==null?null:supplier.getName()).suggestedQty(display).approvedQty(display).directDemandBase(d.direct).recipeDemandBase(d.recipe).totalDemandBase(d.total()).suggestedQtyBase(suggested).approvedQtyBase(suggested).unitCost(cost==null?BigDecimal.ZERO:cost).confidence(d.confidence).build());}
  return response(repository.save(plan));
 }
 @Transactional(readOnly=true) public List<ReorderPlanResponse> list(){User u=security.getCurrentUser();return (security.isAdminLike(u)?repository.findAllByOrderByCreatedAtDesc():repository.findByBranchIdOrderByCreatedAtDesc(u.getBranchId())).stream().map(this::response).toList();}
 @Transactional(readOnly=true) public ReorderPlanResponse get(Long id){return response(plan(id));}
 @Transactional @Audited(entity="REORDER_PLAN",action="EDIT_LINE",idExpression="#id")
 public ReorderPlanResponse updateLine(Long id,Long lineId,ReorderLineUpdateRequest request){ReorderPlan p=editable(id); ReorderPlanLine l=p.getLines().stream().filter(x->Objects.equals(x.getId(),lineId)).findFirst().orElseThrow(()->new ResourceNotFoundException("Reorder plan line not found")); if(request.approvedQty()==null||request.approvedQty().signum()<0)throw new BadRequestException("approvedQty must be zero or greater");Item item=items.findById(l.getItemId()).orElseThrow(()->new ResourceNotFoundException("Item not found"));long approvedBase=request.approvedQty().signum()==0?0:QuantityConversionUtil.normalizeQuantity(item,request.approvedQty(),QuantityConversionUtil.primaryDisplayUnit(item));l.setApprovedQty(QuantityConversionUtil.toDisplayQuantity(item,Math.toIntExact(approvedBase)));l.setApprovedQtyBase(approvedBase);if(request.supplierId()==null){l.setSupplierId(null);l.setSupplierName(null);}else{var s=suppliers.findById(request.supplierId()).filter(x->Boolean.TRUE.equals(x.getActive())).orElseThrow(()->new BadRequestException("Supplier is not active"));l.setSupplierId(s.getId());l.setSupplierName(s.getName());}l.setExcluded(request.excluded());l.setEditNote(request.editNote());l.setManuallyEdited(true);return response(repository.save(p));}
 @Transactional @Audited(entity="REORDER_PLAN",action="SUBMIT",idExpression="#id") public ReorderPlanResponse submit(Long id){ReorderPlan p=editable(id);if(p.getLines().stream().noneMatch(l->!l.isExcluded()&&l.getApprovedQty().signum()>0))throw new BadRequestException("Plan has no actionable lines");p.setStatus(ReorderPlanStatus.PENDING_APPROVAL);p.setSubmittedAt(LocalDateTime.now());return response(repository.save(p));}
 @Transactional @Audited(entity="REORDER_PLAN",action="APPROVE",idExpression="#id") public ReorderPlanResponse approve(Long id){ReorderPlan p=plan(id);require(p,ReorderPlanStatus.PENDING_APPROVAL);p.setStatus(ReorderPlanStatus.APPROVED);p.setApprovedAt(LocalDateTime.now());p.setApprovedByUsername(security.getCurrentUser().getUsername());return response(repository.save(p));}
 @Transactional @Audited(entity="REORDER_PLAN",action="REJECT",idExpression="#id") public ReorderPlanResponse reject(Long id,String reason){if(reason==null||reason.isBlank())throw new BadRequestException("reason is required");ReorderPlan p=plan(id);require(p,ReorderPlanStatus.PENDING_APPROVAL);p.setStatus(ReorderPlanStatus.REJECTED);p.setRejectedAt(LocalDateTime.now());p.setRejectReason(reason.trim());return response(repository.save(p));}
 @Transactional(readOnly=true) public List<PurchaseDraftResponse> purchaseDrafts(Long id){ReorderPlan p=plan(id);require(p,ReorderPlanStatus.APPROVED);var active=p.getLines().stream().filter(l->!l.isExcluded()&&l.getApprovedQty().signum()>0).toList();if(active.stream().anyMatch(l->l.getSupplierId()==null))throw new BadRequestException("Assign suppliers to all active lines before conversion");return active.stream().collect(Collectors.groupingBy(ReorderPlanLine::getSupplierId,LinkedHashMap::new,Collectors.toList())).entrySet().stream().map(e->{var lines=e.getValue();var items=lines.stream().map(l->new PurchaseDraftResponse.Item(l.getItemId(),l.getItemName(),l.getUnit(),l.getApprovedQty(),l.getUnitCost())).toList();BigDecimal total=lines.stream().map(l->l.getApprovedQty().multiply(l.getUnitCost())).reduce(BigDecimal.ZERO,BigDecimal::add);return new PurchaseDraftResponse(e.getKey(),lines.get(0).getSupplierName(),p.getBranchId(),items,total);}).toList();}
 @Transactional @Audited(entity="REORDER_PLAN",action="HANDOFF",idExpression="#id") public ReorderPlanResponse markConverted(Long id,MarkHandoffRequest request){if(request==null||request.reference()==null||request.reference().isBlank())throw new BadRequestException("handoff reference is required");ReorderPlan p=plan(id);require(p,ReorderPlanStatus.APPROVED);p.setStatus(ReorderPlanStatus.CONVERTED);p.setConvertedAt(LocalDateTime.now());p.setConvertedByUsername(security.getCurrentUser().getUsername());p.setHandoffReference(request.reference().trim());return response(repository.save(p));}
 private ReorderPlan editable(Long id){ReorderPlan p=plan(id);require(p,ReorderPlanStatus.DRAFT);return p;} private ReorderPlan plan(Long id){ReorderPlan p=repository.findById(id).orElseThrow(()->new ResourceNotFoundException("Reorder plan not found"));security.enforceBranchAccess(p.getBranchId());return p;} private void require(ReorderPlan p,ReorderPlanStatus s){if(p.getStatus()!=s)throw new BadRequestException("Plan must be "+s);} private BigDecimal decimal(double v){return BigDecimal.valueOf(v).setScale(3,RoundingMode.HALF_UP);}
  private ReorderPlanResponse response(ReorderPlan p){return new ReorderPlanResponse(p.getId(),p.getName(),p.getBranchId(),p.getStatus(),p.getForecastDays(),p.getTargetCoverDays(),p.getCreatedByUsername(),p.getCreatedAt(),p.getSubmittedAt(),p.getApprovedAt(),p.getApprovedByUsername(),p.getRejectReason(),p.getConvertedAt(),p.getConvertedByUsername(),p.getHandoffReference(),p.getNotes(),p.getLines().stream().map(l->new ReorderPlanResponse.Line(l.getId(),l.getItemId(),l.getItemName(),l.getItemType()==null?"NORMAL":l.getItemType().name(),l.getUnit(),l.getSupplierId(),l.getSupplierName(),l.getSuggestedQty(),l.getApprovedQty(),l.getDirectDemandBase(),l.getRecipeDemandBase(),l.getTotalDemandBase(),l.getSuggestedQtyBase(),l.getApprovedQtyBase(),l.getUnitCost(),l.getConfidence(),l.isExcluded(),l.isManuallyEdited(),l.getEditNote())).toList());}
 private static final class DemandAccumulator{long direct;long recipe;String confidence="INSUFFICIENT";void addDirect(long v,String c){direct=Math.addExact(direct,v);promote(c);}void addRecipe(long v,String c){recipe=Math.addExact(recipe,v);promote(c);}long total(){return Math.addExact(direct,recipe);}void promote(String c){if(rank(c)>rank(confidence))confidence=c;}static int rank(String c){return switch(c==null?"":c){case"HIGH"->4;case"MEDIUM"->3;case"LOW"->2;default->1;};}}
}
