package com.chala.posapp.service;
import com.chala.posapp.audit.Audited; import com.chala.posapp.dto.reorder.*; import com.chala.posapp.entity.User; import com.chala.posapp.entity.reorder.*; import com.chala.posapp.entity.supplier.SupplierItem; import com.chala.posapp.exception.*; import com.chala.posapp.repository.*; import com.chala.posapp.util.SecurityUtils; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.math.*; import java.time.LocalDateTime; import java.util.*; import java.util.stream.Collectors;
@Service @RequiredArgsConstructor
public class ReorderPlanService {
 private final ReorderPlanRepository repository; private final SupplierItemReadRepository supplierItems; private final SupplierRepository suppliers; private final NewReportService reports; private final SecurityUtils security;
 @Transactional @Audited(entity="REORDER_PLAN",action="CREATE")
 public ReorderPlanResponse create(ReorderPlanRequest request){
  if(request==null||request.name()==null||request.name().isBlank())throw new BadRequestException("name is required");
  Long branch=security.enforceBranchAccess(request.branchId()); User user=security.getCurrentUser();
  var forecast=reports.demandForecast(branch,request.forecastDays(),request.targetCoverDays(),null,null,null,true);
  ReorderPlan plan=ReorderPlan.builder().name(request.name().trim()).branchId(branch).forecastDays(request.forecastDays()).targetCoverDays(request.targetCoverDays()).createdByUserId(user.getId()).createdByUsername(user.getUsername()).notes(request.notes()).build();
  for(var item:forecast.getItems()){
   SupplierItem mapping=supplierItems.findByItemIdAndSupplierActiveTrueOrderByPrimarySupplierDescIdAsc(item.getItemId()).stream().findFirst().orElse(null);
   var supplier=mapping==null?null:mapping.getSupplier(); BigDecimal cost=mapping!=null&&mapping.getLastBuyingPrice()!=null?BigDecimal.valueOf(mapping.getLastBuyingPrice()):BigDecimal.valueOf(item.getEstimatedReorderCost()).divide(BigDecimal.valueOf(Math.max(item.getSuggestedReorderQty(),1)),3,RoundingMode.HALF_UP);
   plan.getLines().add(ReorderPlanLine.builder().plan(plan).itemId(item.getItemId()).itemName(item.getItemName()).unit(item.getUnit()).supplierId(supplier==null?null:supplier.getId()).supplierName(supplier==null?null:supplier.getName()).suggestedQty(decimal(item.getSuggestedReorderQty())).approvedQty(decimal(item.getSuggestedReorderQty())).unitCost(cost).confidence(item.getConfidence()).build());
  }
  return response(repository.save(plan));
 }
 @Transactional(readOnly=true) public List<ReorderPlanResponse> list(){User u=security.getCurrentUser();return (security.isAdminLike(u)?repository.findAllByOrderByCreatedAtDesc():repository.findByBranchIdOrderByCreatedAtDesc(u.getBranchId())).stream().map(this::response).toList();}
 @Transactional(readOnly=true) public ReorderPlanResponse get(Long id){return response(plan(id));}
 @Transactional @Audited(entity="REORDER_PLAN",action="EDIT_LINE",idExpression="#id")
 public ReorderPlanResponse updateLine(Long id,Long lineId,ReorderLineUpdateRequest request){ReorderPlan p=editable(id); ReorderPlanLine l=p.getLines().stream().filter(x->Objects.equals(x.getId(),lineId)).findFirst().orElseThrow(()->new ResourceNotFoundException("Reorder plan line not found")); if(request.approvedQty()==null||request.approvedQty().signum()<0)throw new BadRequestException("approvedQty must be zero or greater"); l.setApprovedQty(request.approvedQty());if(request.supplierId()==null){l.setSupplierId(null);l.setSupplierName(null);}else{var s=suppliers.findById(request.supplierId()).filter(x->Boolean.TRUE.equals(x.getActive())).orElseThrow(()->new BadRequestException("Supplier is not active"));l.setSupplierId(s.getId());l.setSupplierName(s.getName());}l.setExcluded(request.excluded());l.setEditNote(request.editNote());l.setManuallyEdited(true);return response(repository.save(p));}
 @Transactional @Audited(entity="REORDER_PLAN",action="SUBMIT",idExpression="#id") public ReorderPlanResponse submit(Long id){ReorderPlan p=editable(id);if(p.getLines().stream().noneMatch(l->!l.isExcluded()&&l.getApprovedQty().signum()>0))throw new BadRequestException("Plan has no actionable lines");p.setStatus(ReorderPlanStatus.PENDING_APPROVAL);p.setSubmittedAt(LocalDateTime.now());return response(repository.save(p));}
 @Transactional @Audited(entity="REORDER_PLAN",action="APPROVE",idExpression="#id") public ReorderPlanResponse approve(Long id){ReorderPlan p=plan(id);require(p,ReorderPlanStatus.PENDING_APPROVAL);p.setStatus(ReorderPlanStatus.APPROVED);p.setApprovedAt(LocalDateTime.now());p.setApprovedByUsername(security.getCurrentUser().getUsername());return response(repository.save(p));}
 @Transactional @Audited(entity="REORDER_PLAN",action="REJECT",idExpression="#id") public ReorderPlanResponse reject(Long id,String reason){if(reason==null||reason.isBlank())throw new BadRequestException("reason is required");ReorderPlan p=plan(id);require(p,ReorderPlanStatus.PENDING_APPROVAL);p.setStatus(ReorderPlanStatus.REJECTED);p.setRejectedAt(LocalDateTime.now());p.setRejectReason(reason.trim());return response(repository.save(p));}
 @Transactional(readOnly=true) public List<PurchaseDraftResponse> purchaseDrafts(Long id){ReorderPlan p=plan(id);require(p,ReorderPlanStatus.APPROVED);var active=p.getLines().stream().filter(l->!l.isExcluded()&&l.getApprovedQty().signum()>0).toList();if(active.stream().anyMatch(l->l.getSupplierId()==null))throw new BadRequestException("Assign suppliers to all active lines before conversion");return active.stream().collect(Collectors.groupingBy(ReorderPlanLine::getSupplierId,LinkedHashMap::new,Collectors.toList())).entrySet().stream().map(e->{var lines=e.getValue();var items=lines.stream().map(l->new PurchaseDraftResponse.Item(l.getItemId(),l.getItemName(),l.getUnit(),l.getApprovedQty(),l.getUnitCost())).toList();BigDecimal total=lines.stream().map(l->l.getApprovedQty().multiply(l.getUnitCost())).reduce(BigDecimal.ZERO,BigDecimal::add);return new PurchaseDraftResponse(e.getKey(),lines.get(0).getSupplierName(),p.getBranchId(),items,total);}).toList();}
 @Transactional @Audited(entity="REORDER_PLAN",action="HANDOFF",idExpression="#id") public ReorderPlanResponse markConverted(Long id,MarkHandoffRequest request){if(request==null||request.reference()==null||request.reference().isBlank())throw new BadRequestException("handoff reference is required");ReorderPlan p=plan(id);require(p,ReorderPlanStatus.APPROVED);p.setStatus(ReorderPlanStatus.CONVERTED);p.setConvertedAt(LocalDateTime.now());p.setConvertedByUsername(security.getCurrentUser().getUsername());p.setHandoffReference(request.reference().trim());return response(repository.save(p));}
 private ReorderPlan editable(Long id){ReorderPlan p=plan(id);require(p,ReorderPlanStatus.DRAFT);return p;} private ReorderPlan plan(Long id){ReorderPlan p=repository.findById(id).orElseThrow(()->new ResourceNotFoundException("Reorder plan not found"));security.enforceBranchAccess(p.getBranchId());return p;} private void require(ReorderPlan p,ReorderPlanStatus s){if(p.getStatus()!=s)throw new BadRequestException("Plan must be "+s);} private BigDecimal decimal(double v){return BigDecimal.valueOf(v).setScale(3,RoundingMode.HALF_UP);}
 private ReorderPlanResponse response(ReorderPlan p){return new ReorderPlanResponse(p.getId(),p.getName(),p.getBranchId(),p.getStatus(),p.getForecastDays(),p.getTargetCoverDays(),p.getCreatedByUsername(),p.getCreatedAt(),p.getSubmittedAt(),p.getApprovedAt(),p.getApprovedByUsername(),p.getRejectReason(),p.getConvertedAt(),p.getConvertedByUsername(),p.getHandoffReference(),p.getNotes(),p.getLines().stream().map(l->new ReorderPlanResponse.Line(l.getId(),l.getItemId(),l.getItemName(),l.getUnit(),l.getSupplierId(),l.getSupplierName(),l.getSuggestedQty(),l.getApprovedQty(),l.getUnitCost(),l.getConfidence(),l.isExcluded(),l.isManuallyEdited(),l.getEditNote())).toList());}
}
