spring.application.name=pos-backend
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/pos_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
app.jwt.secret=8f3dA2kL9xQ7mV1pR6sT0yN4cJ2hG5wZ
app.jwt.expiration=86400000

#spring.datasource.url=jdbc:mysql://u73_UGxjqdbLfT:O5v77bB9%3D%40GNQtT3u%40.n8v5N@142.44.214.156:3306/s73_pos_db?createDatabaseIfNotExist=true
#spring.datasource.username=u73_UGxjqdbLfT
#spring.datasource.password=O5v77bB9=@GNQtT3u@.n8v5N